### ISSUE TITLE
HTTP response body not always closed

### ISSUE THREAD

**Issue by freedge** [stackrox/docker-registry-client#18]
same as https://github.com/heroku/docker-registry-client/pull/98

the following code
https://github.com/stackrox/docker-registry-client/blob/master/registry/tokentransport.go#L74-L77
fails to close the body if response.StatusCode != http.StatusOK and a socket is leaked

**Comment by RTann** [comment]
Thank you for bringing this to our attention! I created #19 in hopes to address this.

We also do not actively work on this, and we are in the process of switching over to https://github.com/google/go-containerregistry. That repo is actively maintained, though it does not support Docker Schema 1 (though nobody should really be using that anymore, anyway). If possible, I'd recommend using that or some other repo which is more actively maintained than this one.

**Comment by freedge** [comment]
hi thanks for the response! well feel free to reject this ticket. While I am using heroku's docker registry client (and found sockets going up the roof) I was mostly intrigued with stackrox usage of it. If you're switching to a better client then I'm not too concerned anymore. Cheers!

**Comment by RTann** [comment]
I merged #19 though when looking through it some more, I realized that this repo is not affected by the memory leak due to https://github.com/stackrox/docker-registry-client/blob/main/registry/tokentransport.go#L52 which was introduced by https://github.com/stackrox/docker-registry-client/pull/7. Because of this, #19 now just makes it clear the returned `err == nil` and it also fixes an unrelated potential panic

**Comment by RTann** [comment]
If you agree with ^, then I will close this issue. Thanks!

**Comment by freedge** [comment]
awesome, Thanks!
